MODEL:
  RESNETS:
    STEM_FUNC: "StemWithGN"
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
    ANCHOR_SIZES: (128, 256, 512)
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("wheat_dataset_train", "wheat_dataset_val")
  TEST: ("wheat_dataset_val",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (20000, )
  MAX_ITER: 40000
  IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 5000
  TEST_PERIOD: 1000
TEST:
  IMS_PER_BATCH: 1
OUTPUT_DIR: "./models/default_20200513"
